import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import SessionAuthProvider from "@/context/SessionAuthProvider";
import Navbar from "./components/layout/Navbar";

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={`${roboto.className} dark:bg-main`}>
        <SessionAuthProvider>
          {/* <Navbar /> */}
          {children}
          </SessionAuthProvider>
        </body>
    </html>
  );
}
